---
services:
  databass:
    restart: always
    container_name: databass
    depends_on:
      - postgres
    image: ghcr.io/chunned/databass:latest
    ports:
      - ${APP_PORT}:8080
    environment:
      - TZ=${TIMEZONE}           # e.g. America/New York
      - TIMEZONE=${TIMEZONE}           # e.g. America/New York
      - DISCOGS_KEY=${DISCOGS_KEY}
      - DISCOGS_SECRET=${DISCOGS_SECRET}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOSTNAME=${PG_HOSTNAME}
      - DB_NAME=${DB_NAME}
      - PG_PORT=${PG_PORT}
      - DB_FILENAME=${SQLITE_DB}
      - VERSION=${VERSION}
      - DOCKER=True
    volumes:
      - ./${SQLITE_DB}/:/databass/${SQLITE_DB}
      - ./images:/databass/static/img
  postgres:
    image: postgres
    restart: always
    container_name: ${PG_HOSTNAME}
    environment:
      - TZ=${TIMEZONE}           # e.g. America/New York
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
