---
services:
  databass:
    container_name: databass
    image: ghcr.io/chunned/databass:latest
    ports:
      - 10111:8080
    environment:
      - DISCOGS_KEY=
      - DISCOGS_SECRET=
      - DB_FILENAME=
      - TIMEZONE=           # e.g. America/New York
    volumes:
      # - .DB_FILENAME/:/databass/DB_FILENAME.db