name: CI Pipeline

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u chunned --password-stdin
      - name: Build and push image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker build . -t ghcr.io/chunned/databass:latest -t ghcr.io/chunned/databass:$TAG 
          docker push ghcr.io/chunned/databass:$TAG
          docker push ghcr.io/chunned/databass:latest
